#!/usr/local/bin/php
<?php
/*
 * setup.php — render /usr/local/bandwidthd/etc/bandwidthd.conf from config.xml.
 *
 * bandwidthd takes no config-path argument, so the file has to land at that exact
 * path. Generating it in PHP (rather than a Jinja template) lets us reuse the
 * platform layer's interface/subnet resolution, which Jinja has no helper for.
 *
 * Run by the rc script's start_precmd and by "configctl bandwidthd configure".
 *
 * Copyright (C) 2026 opnsense-bandwidthd contributors
 * Licensed under the Apache License, Version 2.0.
 */

require_once('/usr/local/opnsense/scripts/OPNsense/Bandwidthd/lib/bwd_platform.inc.php');

$conf_dir = BWD_BASE . '/etc';
if (!is_dir($conf_dir)) {
	safe_mkdir($conf_dir);
}

$lines = array();
$lines[] = '# Generated by the OPNsense BandwidthD plugin — do not edit.';
$lines[] = '# Change these settings under Services -> BandwidthD -> Settings.';
$lines[] = '# Written ' . date('c');
$lines[] = '';

/* Local subnets. Traffic between one of these and anything outside it is
 * attributed to the local device; traffic matching none of them is ignored. */
$subnets = bwd_platform_subnets();
foreach (preg_split('/[,;\s]+/', (string) bwd_cfg('subnets_extra', ''), -1, PREG_SPLIT_NO_EMPTY) as $sn) {
	$p = explode('/', $sn);
	if (count($p) === 2 && is_ipaddrv4($p[0]) && ctype_digit($p[1]) && (int) $p[1] <= 32) {
		$subnets[] = $sn;
	}
}
if (!$subnets) {
	/* Never emit a config with no subnets: bandwidthd would then count nothing. */
	$subnets[] = '192.168.0.0/16';
	$subnets[] = '10.0.0.0/8';
	$subnets[] = '172.16.0.0/12';
}
$lines[] = '# Subnets to collect statistics on.';
foreach (array_unique($subnets) as $sn) {
	$lines[] = "subnet $sn";
}
$lines[] = '';

/* The capture device. One only — bandwidthd opens a single pcap handle. */
$ifName = (string) bwd_cfg('interface', 'lan');
$dev = bwd_platform_realif($ifName);
/* If the assignment is gone, realif falls back to the symbolic name ("opt2"),
 * which writes a config the daemon then dies on at pcap-open time with the error
 * only in syslog. Fail here instead, where the message reaches the operator. */
if ($dev === $ifName && !bwd_device_exists($dev)) {
	fwrite(STDERR, "capture interface '$ifName' is not assigned to a device; "
		. "pick an existing interface under Services -> BandwidthD -> Settings\n");
	exit(1);
}
$lines[] = '# Device to listen on.';
$lines[] = 'dev "' . $dev . '"';
$lines[] = '';

$lines[] = 'promiscuous ' . (bwd_cfg_on('promiscuous') ? 'true' : 'false');
$lines[] = 'graph ' . (bwd_cfg_on('drawgraphs') ? 'true' : 'false');
/* CDF output is what the dashboard reads. */
$lines[] = 'output_cdf ' . (bwd_cfg_on('outputcdf') ? 'true' : 'false');
if (bwd_cfg_on('recovercdf')) {
	$lines[] = 'recover_cdf true';
}

$skip = (string) bwd_cfg('skipintervals', '');
if ($skip !== '' && ctype_digit($skip)) {
	$lines[] = "skip_intervals $skip";
}
$cutoff = (string) bwd_cfg('graphcutoff', '');
if ($cutoff !== '' && ctype_digit($cutoff)) {
	$lines[] = "graph_cutoff $cutoff";
}
$sensor = trim((string) bwd_cfg('sensorid', ''));
if ($sensor !== '') {
	$lines[] = 'sensor_id "' . str_replace('"', '', $sensor) . '"';
}
/* A libpcap filter restricting what is counted. Always keep "ip" in it. */
$filter = trim((string) bwd_cfg('advfilter', ''));
if ($filter !== '') {
	$lines[] = 'filter "' . str_replace('"', '', $filter) . '"';
}

$out = implode("\n", $lines) . "\n";
$target = $conf_dir . '/bandwidthd.conf';
if (!bwd_atomic_write_raw($target, $out)) {
	fwrite(STDERR, "failed to write $target\n");
	exit(1);
}

/* bandwidthd writes its CDF logs and PNG output into these. */
foreach (array(BWD_BASE . '/htdocs', BWD_BASE . '/rollups') as $d) {
	safe_mkdir($d);
}
/* The rollups are the household's device inventory; every reader runs as root. */
@chmod(BWD_BASE . '/rollups', 0700);

/* Reset the probe auto-off clock whenever probing is off.
 *
 * probe_state.json records when probing was switched on, and the cron pass turns
 * probing back off once probe_auto_off_hours have elapsed. If the operator
 * disables probing by hand before that fires, a stale enabled_at survives — and
 * on re-enable the very next cron pass sees the window already exceeded and
 * immediately disables probing again, having fingerprinted nothing. Clearing it
 * here (setup.php runs on every reconfigure and on daemon start) restarts the
 * clock. */
if (!bwd_cfg_on('probe_enable')) {
	@unlink(BWD_BASE . '/rollups/probe_state.json');
}

echo "OK\n";

/* Is this a real network device on the box? */
function bwd_device_exists($dev) {
	$out = array();
	@exec('/sbin/ifconfig -l 2>/dev/null', $out);
	$all = preg_split('/\s+/', trim(implode(' ', $out)), -1, PREG_SPLIT_NO_EMPTY);
	return in_array($dev, $all, true);
}

/* Minimal atomic write — setup.php runs before the full data layer is loaded. */
function bwd_atomic_write_raw($file, $contents) {
	$tmp = @tempnam(dirname($file), '.bwd');
	if ($tmp === false) { return false; }
	if (@file_put_contents($tmp, $contents) === false) { @unlink($tmp); return false; }
	@chmod($tmp, 0600);
	if (!@rename($tmp, $file)) { @unlink($tmp); return false; }
	return true;
}
